In [1]:
import pandas as pd
df = pd.read_csv('labelled.csv')
df

,image,id,label,annotator,annotation_id,created_at,updated_at,lead_time
0,/data/upload/1/a576e59d-drowsy.63b4814d-6bb2-1...,113,"[{""x"": 25.679347826086957, ""y"": 43.11594202898...",1,180,2022-12-08T01:41:07.654645Z,2022-12-08T01:41:07.654645Z,4.477
1,/data/upload/1/a768538b-drowsy.34dcad33-6bb2-1...,112,"[{""x"": 36.95652173913042, ""y"": 40.217391304347...",1,179,2022-12-08T01:41:00.343052Z,2022-12-08T01:41:00.343052Z,4.633
2,/data/upload/1/3c707e2d-drowsy.f9162747-6bb1-1...,175,"[{""x"": 39.67391304347825, ""y"": 46.920289855072...",1,178,2022-12-08T01:40:00.292704Z,2022-12-08T01:40:00.292704Z,3.560
3,/data/upload/1/197ac555-drowsy.f7def662-6f9b-1...,174,"[{""x"": 34.78260869565217, ""y"": 19.202898550724...",1,177,2022-12-08T01:39:56.452259Z,2022-12-08T01:39:56.452259Z,3.582
4,/data/upload/1/32f308a7-drowsy.f7c14b91-6f33-1...,173,"[{""x"": 23.505434782608695, ""y"": 4.710144927536...",1,176,2022-12-08T01:39:52.320679Z,2022-12-08T01:39:52.320679Z,7.805
...,...,...,...,...,...,...,...,...
170,/data/upload/1/a7e6fea2-awake.3d899d19-748a-11...,5,"[{""x"": 52.85326086956522, ""y"": 38.768115942028...",1,5,2022-12-08T00:05:32.503864Z,2022-12-08T01:20:12.594412Z,7.872
171,/data/upload/1/361bf690-awake.0be8a1aa-6f99-11...,1,"[{""x"": 26.4945652173913, ""y"": 27.8985507246376...",1,26,2022-12-08T01:20:00.435153Z,2022-12-08T01:20:00.435153Z,26.522
172,/data/upload/1/40a057d0-awake.1f4943a1-6f83-11...,2,"[{""x"": 36.005434782608695, ""y"": 22.10144927536...",1,25,2022-12-08T01:19:30.266910Z,2022-12-08T01:19:30.266910Z,7.093
173,/data/upload/1/bd16a6bf-awake.3b1d20f9-6f99-11...,4,"[{""x"": 39.266304347826086, ""y"": 11.77536231884...",1,4,2022-12-08T00:05:29.296960Z,2022-12-08T01:19:10.302836Z,9.017
174,/data/upload/1/4f30c027-awake.2f21cc55-6bb0-11...,3,"[{""x"": 31.52173913043478, ""y"": 50, ""width"": 30...",1,3,2022-12-08T00:05:25.600667Z,2022-12-08T01:19:00.641976Z,9.384

In [2]:
print(df['label'])

0      [{"x": 25.679347826086957, "y": 43.11594202898...
1      [{"x": 36.95652173913042, "y": 40.217391304347...
2      [{"x": 39.67391304347825, "y": 46.920289855072...
3      [{"x": 34.78260869565217, "y": 19.202898550724...
4      [{"x": 23.505434782608695, "y": 4.710144927536...
                             ...
170    [{"x": 52.85326086956522, "y": 38.768115942028...
171    [{"x": 26.4945652173913, "y": 27.8985507246376...
172    [{"x": 36.005434782608695, "y": 22.10144927536...
173    [{"x": 39.266304347826086, "y": 11.77536231884...
174    [{"x": 31.52173913043478, "y": 50, "width": 30...
Name: label, Length: 175, dtype: object

In [6]:
print(df['label'][0])

[{"x": 25.679347826086957, "y": 43.11594202898551, "width": 44.97282608695652, "height": 56.702898550724626, "rotation": 0, "rectanglelabels": ["Drowsy"], "original_width": 640, "original_height": 480}]

In [80]:
#Ubah df['label'] ke df sendiri
label = df['label']

df_final = pd.DataFrame()

for i in range(len(label)):
    l = label[i]
    df1 = pd.DataFrame(eval(l))
    df_final = pd.concat([df_final, df1], axis=0)
    
df_final = df_final.reset_index()

In [81]:
#ubah rectanglelabels dari list ke str
df_final['rectanglelabels'] = [''.join(map(str,  l)) for l in df_final['rectanglelabels']]

In [82]:
df_final

,index,x,y,width,height,rotation,rectanglelabels,original_width,original_height
0,0,25.679348,43.115942,44.972826,56.702899,0,Drowsy,640,480
1,0,36.956522,40.217391,36.956522,57.246377,0,Drowsy,640,480
2,0,39.673913,46.920290,32.608696,53.079710,0,Drowsy,640,480
3,0,34.782609,19.202899,40.217391,66.123188,0,Drowsy,640,480
4,0,23.505435,4.710145,44.429348,74.637681,0,Drowsy,640,480
...,...,...,...,...,...,...,...,...,...
170,0,52.853261,38.768116,33.423913,59.239130,0,Awake,640,480
171,0,26.494565,27.898551,32.201087,67.391304,0,Awake,640,480
172,0,36.005435,22.101449,38.994565,74.818841,0,Awake,640,480
173,0,39.266304,11.775362,40.760870,73.731884,0,Awake,640,480
174,0,31.521739,50.000000,30.978261,45.289855,0,Awake,640,480

In [83]:
df_dipake = df_final[['x', 'y', 'width', 'height', 'rectanglelabels']]
df_dipake

             x          y      width     height rectanglelabels
0    25.679348  43.115942  44.972826  56.702899          Drowsy
1    36.956522  40.217391  36.956522  57.246377          Drowsy
2    39.673913  46.920290  32.608696  53.079710          Drowsy
3    34.782609  19.202899  40.217391  66.123188          Drowsy
4    23.505435   4.710145  44.429348  74.637681          Drowsy
..         ...        ...        ...        ...             ...
170  52.853261  38.768116  33.423913  59.239130           Awake
171  26.494565  27.898551  32.201087  67.391304           Awake
172  36.005435  22.101449  38.994565  74.818841           Awake
173  39.266304  11.775362  40.760870  73.731884           Awake
174  31.521739  50.000000  30.978261  45.289855           Awake

[175 rows x 5 columns]

In [85]:
df_dipake.to_csv('labelled_final.csv')